version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432


  rabbitMQ:
    image: rabbitmq:3-management
    container_name: demo-rabbit-jdbc-transaction
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAUT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672